# Generated by Django 4.1 on 2022-08-23 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_incomemodel_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemodel',
            name='report_expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='report.reportmodel'),
        ),
    ]
